version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=localhost
